### ISSUE TITLE
Splitting tags with more than three attributes into multiple lines

### ISSUE THREAD

**Issue by akiran** [royriojas/esformatter-jsx#1]
Can we have a options to transform this
```html
<div className='classes' style={style} onClick={this.click} onMouseDown={this.start} onMouseMove={this.move} onMouseUp={this.stop} >Element</div>
```
into
```html
<div 
    className='classes'
    style={style}
    onClick={this.click}
    onMouseDown={this.start}
    onMouseMove={this.move}
    onMouseUp={this.stop} >
    Element
</div>
```

**Comment by royriojas** [comment]
I was actually wanting to make this also. I'm currently just passing the jsx elements directly to the js-beautify html beautifier, and that one puts everything in a line. It might be simple to do using fresh-falafel, my only concern is that maintaining the alignment, but let's see if it can be done.

**Comment by akiran** [comment]
@royriojas Thanks for prompt response. I will test it in my project.

**Comment by royriojas** [comment]
You're welcome! 

Use the latest version, the previous one had some unpredictable behavior. Check the unit tests to have a better idea of how it works.
