### ISSUE TITLE
Missing trailing comma

### ISSUE THREAD

**Issue by lixingdecai** [royriojas/esformatter-jsx#109]
when i use the the beutify, the last comma is disappear , like this 
![image](https://user-images.githubusercontent.com/19658346/31592174-f5102468-b1eb-11e7-887f-f1cf7975bb18.png)

and i cant find where and how to set. i use the "comma_first" and "end_with_comma" ,but it didnt work
![image](https://user-images.githubusercontent.com/19658346/31592201-2a64f31e-b1ec-11e7-8d6e-b83d05f0e76a.png)

i think its important,  what can i do

**Comment by royriojas** [comment]
hi @lixingdecai, It seems there is a misunderstanding, the configuration for esformatter settings should be set in the `.esformatter.json` file not `.jsbeautifyrc`
