### ISSUE TITLE
How to avoid spacing after braces?

### ISSUE THREAD

**Issue by vvo** [royriojas/esformatter-jsx#11]
I cannot find a configuration use esformatter-jsx where I do not have spacing around braces.

how to?

**Comment by royriojas** [comment]
Hi @vvo currently there is no such option, however adding it won't be that complicated. 

But just to clarify

what you're looking is for an option for transforming

```javascript
<a className={ className } > foo </a>
```

to

```javascript
<a className={className} > foo </a>
```

right?

**Comment by vvo** [comment]
Yes that's it, I do not want spaces after or before braces

**Comment by royriojas** [comment]
hi @vvo check: the option added is `spaceInJSXExpressionContainers` (check the config)

http://goo.gl/DiY08J

**Comment by vvo** [comment]
awesome @royriojas :clap: :)
