### ISSUE TITLE
inline attribute length

### ISSUE THREAD

**Issue by spencermountain** [royriojas/esformatter-jsx#12]
hey man, got one more maybe:
it seems if the inline attributes are over a certain number of characters, it breaks the closing tag into a new line

this one breaks:
```<MyElement a={ 1 } b={1} c={ 1 } d={ 1 } e={ 1 } abcdefghijklmnop={ i }/>```

this one doesnt:
```<MyElement a={ 1 } b={1} c={ 1 } d={ 1 } e={ 1 } abc={ i }/>```

http://goo.gl/Ubjzk6
cheers

**Comment by royriojas** [comment]
hi @spencermountain try increasing the  `wrap_line_length` option maybe the default I set is too conservative.

click config and check the options in the jsx section

http://goo.gl/pJPp7H

**Comment by spencermountain** [comment]
ah! perfect. thanks man
