### ISSUE TITLE
Unexpected token ILLEGAL

### ISSUE THREAD

**Issue by ipselon** [royriojas/esformatter-jsx#13]
I got following error in online-demo and locally (using esformatter 0.7.3, esformatter-jsx 2.0.6):

    //==> Error: Line 19: Unexpected token ILLEGAL

Is there something wrong in code ?

```
'use strict';

var React = require('react');

var ReactBootstrap = require('../../assets/js/react-bootstrap.min.js');
var Input = ReactBootstrap.Input;
var Button = ReactBootstrap.Button;


var InputWithButton = React.createClass({
    

    getDefaultProps: function () {
        return {};
    },
    
    render: function(){
        return (
            <div {...this.props} >
            
            <p ><span >Basic panel</span></p> 
            <Input type={'text'} placeholder={'Enter value'} addonBefore={'$'} buttonAfter={ <Button bsStyle={'default'} ><span >Default</span></Button> }></Input> 
            
            </div>
        );
    }

});

module.exports = InputWithButton;
```

**Comment by royriojas** [comment]
Mm, It seems that there are some issues with the way the container expressions are treated the following code works for me:

http://goo.gl/uaDGvo 

But that make me realize there might be a bug lurking in the shadows when someone uses single quotes (which is valid) for the attributes. I will provide a fix ASAP

**Comment by ipselon** [comment]
Thanks for quick response.

**Comment by royriojas** [comment]
So I found the issue, somehow ```"$"``` is ok but ```'$'``` is not. It is like it has an special meaning inside the replace method of string, and messes everything. I also found a second bug, that makes the formatter to fail if one of the attributes also contain JSX and is the last attribute. If there are more attributes it will format that correctly, just letting you know about that for now.

**Comment by ipselon** [comment]
Great, your tool is important for me, so I appreciate your attitude.

**Comment by royriojas** [comment]
Got it! hope it helps!

http://goo.gl/mWjTfD

**Comment by ipselon** [comment]
Thanks, it works.
