### ISSUE TITLE
Function inside of attribute causes misformatting of children

### ISSUE THREAD

**Issue by kushal** [royriojas/esformatter-jsx#17]
If I try to format this block http://cl.ly/image/2w0H3I2P3I1I a space is always inserted before the {am} causing an error since the parent node can only have one child node.

The formatting is correct if the attribute does not contain () =>, e.g. http://cl.ly/image/16220h3S3h3T

**Comment by royriojas** [comment]
Hi @kushal, what version of the esformatter-jsx and esformatter are you using?

**Comment by royriojas** [comment]
can you try to replicate the issue here? http://goo.gl/x1hTHG

**Comment by royriojas** [comment]
@kushal any news about this?

**Comment by kushal** [comment]
Sorry for the delay. Versions are 0.7.3 and 1.3.0. I can't repro there, not really sure why?

**Comment by royriojas** [comment]
Can you try to install latest `esformatter-jsx`? 

The last version is 2.0.11

**Comment by kushal** [comment]
Aha, that fixed it!  Thanks!

**Comment by kushal** [comment]
By the way, is there a way to prevent the introduction of a line break in
http://requirebin.com/embed?gist=0d67452e01754269660f#%7B%22config%22%3A%7B%22jsx%22%3A%7B%22attrsOnSameLineAsTag%22%3Afalse%2C%22maxAttrsOnTag%22%3A1%2C%22firstAttributeOnSameLine%22%3Afalse%2C%22alignWithFirstAttribute%22%3Atrue%2C%22spaceInJSXExpressionContainers%22%3A%22%22%7D%7D%2C%22code%22%3A%22%3Cz%3E%5CnHello%20%7B%20am%20%7D%5Cn%3C%2Fz%3E%5Cn%22%7D
 ?

**Comment by royriojas** [comment]
so far not, since the transform introduces spans between `JSXExpressionContainers` it is actually safer to have them in their own new lines. But that can be made optional I guess

**Comment by kushal** [comment]
The challenge is you then have to explicitly add {sp} when you want one.
