### ISSUE TITLE
`jsx` and inline map functions not formatted correct

### ISSUE THREAD

**Issue by leftstick** [royriojas/esformatter-jsx#18]
While i have `render` method as following:

```jsx
render() {
    return (
        <List>
          { this.state.todos.map(function(todo) {
                return <TodoItem key={ todo.id } data={ todo }/>; 
          })}
        </List>
        );
}
```

After formatting with the plugin, i got:

```jsx
render() {
    return (
        <List>
          { this.state.todos.map(function(todo) {
                                              return <TodoItem key={ todo.id } data={ todo }/>;
                                        }) }
        </List>
        );
}
```

And if i re-do the formatting again, i got:
```jsx
render() {
    return (
        <List>
          { this.state.todos.map(function(todo) {
                                                                            return <TodoItem key={ todo.id } data={ todo }/>;
                                                                      }) }
        </List>
        );
}
```

Every time i do formatting, seems the `return` part is moved further.
Strange, and incorrect.

**Comment by royriojas** [comment]
hi @leftstick, 

can you provide your version of `esformatter` and `esformatter-jsx`?

**Comment by leftstick** [comment]
`esformatter` = `0.7.3`
`esformatter-jsx` = `2.0.11`

**Comment by leftstick** [comment]
`esformatter` = `0.7.3`
`esformatter-jsx` = `2.0.11`

**Comment by royriojas** [comment]
mmm, @leftstick, I cannot reproduce the issues with those versions, are you using it in sublime text or as a standalone binary?

**Comment by leftstick** [comment]
I am using those version in `atom`. But it can be reproduced just in [requirebin](http://requirebin.com/embed?gist=0d67452e01754269660f#%7B%22config%22%3A%7B%22jsx%22%3A%7B%22attrsOnSameLineAsTag%22%3Afalse%2C%22maxAttrsOnTag%22%3A1%2C%22firstAttributeOnSameLine%22%3Afalse%2C%22alignWithFirstAttribute%22%3Atrue%7D%7D%2C%22code%22%3A%22%2F%2F%20Paste%20your%20own%20code%20here...%5Cn%5Cn%5Cn%20var%20Comment%20%3D%20React.createClass(%7B%5Cn%20%20render%3A%20function()%20%7B%5Cn%20%20%20%20return%20(%5Cn%20%20%20%20%20%20%20%20%3CList%20style%3D%7BlistStyle%7D%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%7B%20this.state.todos.map(function(todo%2C%20index)%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20return%20%3CTodoItem%20key%3D%7Btodo.id%7D%20data%3D%7Btodo%7D%20isLast%3D%7B_this.state.todos.length%20-1%20%3D%3D%3D%20index%7D%2F%3E%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%7D)%7D%5Cn%20%20%20%20%20%20%20%20%3C%2FList%3E%5Cn%20%20%20%20)%3B%5Cn%20%20%7D%5Cn%7D)%3B%22%7D)


![snip20150820_2](https://cloud.githubusercontent.com/assets/1059956/9384036/e613e4b4-477f-11e5-8ef3-fe2bfd6a7e35.png)

**Comment by royriojas** [comment]
sadly until this is fixed:

https://github.com/millermedeiros/esformatter/issues/348

I cannot update the demo, so that makes me think the version you are using is not the latest one.

I can still provide some help if you provide some details of how you use it in atom, since I'm not familiar with it. 

The latest version seems to be working pretty fine to me:

try this for example:

```bash
# just for the sake of confirming your bug, you can remove it later if you want
npm i -g esbeautifier

# this will format your file, please make a backup or have the file open so you can revert back
# to the original format
esbeautifier path/to/your/file.js 
```

**Comment by leftstick** [comment]
Really weird, I have following plugins installed with `atom`:

`esformatter-semicolons`
`esformatter-braces`
`esformatter-collapse-objects`
`esformatter-dot-notation`
`esformatter-jsx`
`esformatter-literal-notation`
`esformatter-quotes`

While i removed them one by one, i found my issue is caused by `esformatter-semicolons`. The formatting feature works well since i removed it.

Thanks for help
