### ISSUE TITLE
Way to reduce number of spaces in inline style attribute

### ISSUE THREAD

**Issue by ipselon** [royriojas/esformatter-jsx#19]
It there some way to reduce spaces  in inline style ?

```
   <Button bsStyle={ 'default' } style={ {    marginLeft: '0.5em',    width: '120px'} }>
       <span>Default</span>
   </Button>
```

**Comment by royriojas** [comment]
sadly that is happening because we try to put in one line the object being formatted. If we don't that these is what we get:

```javascript
function demo() {

  return <Button
                 bsStyle={ 'default' }
                 style={ {
                           marginLeft: '0.5em',
                           width: '120px'
                         } }>
           <span>Default</span>
         </Button>
}
```
which I don't see it being bad. Probably I should make that an option as well.

**Comment by ipselon** [comment]
Unfortunately, in case of more than 5 components it turns into mess, but in one line without extra spaces it has a good look.

**Comment by royriojas** [comment]
Let me find a way to deal with that. I pass that directly to `esformatter`, so I will find a way to make esformatter deal with that. I could use regexes, but that is really very error prone

**Comment by ipselon** [comment]
Cool! I believe you will find how to make it beautiful.

**Comment by tnrich** [comment]
+1 for this. Great formatter otherwise

**Comment by tnrich** [comment]
Any updates on this front? Thanks!

**Comment by royriojas** [comment]
I will try to update the plugin to be more consistent, also I notice esformatter was updated as well and now it uses babylon as the parser, that might simplify things.

**Comment by jugarrit** [comment]
+1!
Would love a fix for this :)

**Comment by zolrath** [comment]
+1 as well! I'd love to be able to have this be a required step before committing at my work but the strange spacing in objects here is ensuring that I can't at the moment.

**Comment by royriojas** [comment]
@zolrath I have added `JSXExpressionsSingleLine` prop, to try to control whether the Expressions are put in a single line or span several lines.

**Comment by ipselon** [comment]
@royriojas many thanks, it works perfectly.
