### ISSUE TITLE
Element attributes not added to new line

### ISSUE THREAD

**Issue by filipmares** [royriojas/esformatter-jsx#20]
I can't force JSX element attributes to a new line using the setting below.
```
    "formatJSX": true, //Duh! that's the deafault
    "attrsOnSameLineAsTag": false, // move each attribute to its own line
    "maxAttrsOnTag": 1, // if lower or equal than 3 attributes, they will be kept on a single line
    "firstAttributeOnSameLine": true, // keep the first attribute in the same line as the tag
    "alignWithFirstAttribute": true, // do not align attributes with the first tag
    "spaceInJSXExpressionContainers": " ", // default to one space. Make it empty if you don't like spaces between JSXExpressionContainers
    "htmlOptions": { // same as the ones passed to js-beautifier.html
      "brace_style": "collapse",
      "indent_char": " ",
      "indent_size": 4,
      "max_preserve_newlines": 2,
      "preserve_newlines": true
    }
```

**Comment by royriojas** [comment]
can you provide an example of the code you try to beautify?

**Comment by filipmares** [comment]
```
        return (
            <li className="recent-item-container">
              <div className="recent-item-footer">
                <a className="btn btn-link enter-call" style={ styles.enterCallBtn } href={ this.getURL() }>Enter</a>
              </div>
            </li>
            );
```

**Comment by royriojas** [comment]
Seems to be working for me:

http://goo.gl/IB3Ipw

Same configuration as the one you have above.

**Comment by filipmares** [comment]
weird. using https://github.com/ionutvmi/sublime-jsfmt. i wonder if there is a version problem there.

**Comment by royriojas** [comment]
have you followed these instructions?

https://github.com/royriojas/esformatter-jsx/wiki/Usage-with-jsfmt

**Comment by filipmares** [comment]
@royriojas yup

**Comment by royriojas** [comment]
mm, it is weird, I just notice it stopped working for me as well, the formatter is not formatting at all

**Comment by royriojas** [comment]
Apparently https://github.com/ionutvmi/sublime-jsfmt/issues/30 this is something that happened recently and it might not be related to `esformatter-jsx`

**Comment by filipmares** [comment]
ah. will keep an eye on it.

On Wed, Sep 9, 2015 at 4:55 PM Roy Riojas <notifications@github.com> wrote:

> Apparently ionutvmi/sublime-jsfmt#30
> <https://github.com/ionutvmi/sublime-jsfmt/issues/30> this is something
> that happened recently and it might not be related to esformatter-jsx
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/royriojas/esformatter-jsx/issues/20#issuecomment-139075802>
> .
>
-- 
-Filip

**Comment by royriojas** [comment]
It seems that you need to make sure you install again all the plugins that you were using. that make it work again for me

**Comment by filipmares** [comment]
i re-installed sublime-jsfmt and then following the instructions listed above to no avail.

**Comment by ionutvmi** [comment]
@filipmares please make sure you have the latest version of nodejs installed.
If it's still not working please post on the ionutvmi/sublime-jsfmt#30 issue and we will sort it out.
