### ISSUE TITLE
Trouble with jsfmt

### ISSUE THREAD

**Issue by antoinecomte** [royriojas/esformatter-jsx#21]
I followed the instructions [here](https://github.com/royriojas/esformatter-jsx/wiki/Usage-with-jsfmt), but ran into some troubles :

* Could not make it to work unless I added the suggested config into the *Default* config file.
* It works, but changing the configuration parameters does not seem to work as intended. For example changing * attrsOnSameLineAsTag* to false does nothing, attributes are still on the same line as the tag.

**Comment by royriojas** [comment]
Hi @antoinecomte can you provide a bit more of info about your setup?

- version of `esformatter`, `esformatter-jsx`, `jsfmt` 
- a sample of your config file

Just to verify, you can use from the cli this wrapper for esformatter [esbeautifier](https://www.npmjs.com/package/esbeautifier) 

At least that might help to see if there is anything wrong with the plugin itself or it might be the integration with `jsfmt`

**Comment by antoinecomte** [comment]
**Versions:**

esformatter@0.7.3 
esformatter-jsx@2.0.11
jsfmt@0.5.0


My setting are :

**User**

```json 
{
  "autoformat": true,
  "extensions": [
    "js",
    "jsx",
    "sublime-settings"
  ],
  "plugins": [],

}
```

**Default :**

```json 
{
  // autoformat on save
  "autoformat": false,

  // array of extensions for autoformat
  "extensions": ["js", "sublime-settings"],

  // options for jsfmt
  "options": {
    "preset": "jquery",
    "indent": {
      "value": "    "
    },
    // plugins included
    "plugins": [
      "esformatter-jsx"
    // "esformatter-quotes",
    // "esformatter-semicolons",
    // "esformatter-braces",
    // "esformatter-dot-notation"
    ]
  },
  "jsx": {
    "formatJSX": true,
    // change these to your preferred values
    // refer to https://github.com/royriojas/esformatter-jsx#best-configuration for more options
    "attrsOnSameLineAsTag": false,
    "maxAttrsOnTag": 1,
    "firstAttributeOnSameLine": true,
    "alignWithFirstAttribute": true
  },
  "options-JSON": {
    "plugins": [
      "esformatter-quotes"
    ],
    "quotes": {
      "type": "double"
    }
  },
  "node-path": "node",
  "alert-errors": true,
  "ignore-selection": false
}
```

**Comment by antoinecomte** [comment]
Feeling so dumb right now, as I realize my config was totally messed up.
Moving the `jsx`entry under `options` where it belongs fixed things up.
So sorry to have wasted your time
