### ISSUE TITLE
Push tag for new release

### ISSUE THREAD

**Issue by nisaacson** [royriojas/esformatter-jsx#23]
Please push a tag to match the latest version published in the public npmjs registry

```
git tag v2.1.0
git push origin v2.1.0
```

In the future the `npm version` commands are useful since they increment version in package.json and automatically generate a git tag

```
npm version patch
npm publish
git push --tags
```

See https://docs.npmjs.com/cli/version for more infomration

**Comment by royriojas** [comment]
Thanks, I did use npm version, don't know exactly how this got messed up
