### ISSUE TITLE
Line 31: Unexpected token <

### ISSUE THREAD

**Issue by ipselon** [royriojas/esformatter-jsx#3]
var React = require('react');
var ReactBootstrap = require('../../assets/js/react-bootstrap.min.js');
var Input = ReactBootstrap.Input;
var Button = ReactBootstrap.Button;

var ProxyInput = React.createClass({
    
    getInitialState: function(){
        return {
            urlValue: this.props.urlValue
        }    
    },
    
    _handleClearUrlValue: function(e){
        e.stopPropagation();
        e.preventDefault();
        this.setState({
            urlValue: ''
        })
    },
    
    _handleChangeUrlValue: function(e){
        this.setState({
            urlValue: this.refs.inputElement.getValue()
        })
    },

    render: function() {
        return (
            <Input 
                ref='inputElement'
                value={this.state.urlValue}
                type={ 'text'} 
                label={ this.props.label} 
                placeholder={ 'Enter value'} 
                addonBefore={ 'URL:'} 
                onChange={this._handleChangeUrlValue}
                buttonAfter={ <Button 
                                onClick={this._handleClearUrlValue}
                                bsStyle={ 'default'}>
                                <span className={ 'fa fa-times'}></span>
                              </Button> 
                }>
                <Grid>
                    <Row>
                        <Col/>
                    </Row>
                </Grid>
            </Input>
        );
    }

});

module.exports = ProxyInput;

**Comment by royriojas** [comment]
Hi @ipselon, can you try your code here?

http://requirebin.com/embed?gist=0d67452e01754269660f

If you paste your code you will see it is formatted properly can you post your configuration for esformatter and the version of esformatter you are using?

Regards

**Comment by pixelass** [comment]
I got the same problem using it with https://github.com/ionutvmi/sublime-jsfmt in Sublime Text 3

Steps to reproduce

1. install https://github.com/ionutvmi/sublime-jsfmt in sublime
2. add esformatter-jsx in the user-config of that package
3. add jsx to supported formats in the user-config of that package
4. `npm install esformatter-jsx` in sublime-jsfmt root-folder
5. format a .jsx file with pointy brackets (xml)
6. Error returned

### Error:
> ... Unexpected token < 

Maybe this is rather related to the esformatter but I thought I'd post it here since Google led me here.

Cheers

**Comment by royriojas** [comment]
@pixelass check your version of esformatter (do `npm ls esformatter`) in the folder of sublime-jsfmt root, if it is less that 0.7.0 then you might want to install esformatter-jsx@1.0.9 doing `npm i esformatter-jsx@1.0.9` 

Basically the issue is that esformatter lesser than 0.7.0 won't understand jsx, and it required the old trick of replacing the jsx constructs to make it pass thru the parser. esformatter greater or equal than 0.7.0 do understand jsx so need for that trick.

**Comment by pixelass** [comment]
@royriojas it tells me there is no version 1.0.9

> version not found: esformatter-jsx@1.0.9

I tried 1.0.8 but the formatting is just overly wrong 

## example:
#### first `let` starts one level too deep
```js
handleKeyup(e) {
  if (this.props.listen) {
      let charCode = e.which;
      if (charCode === 37 || charCode === 38) {
        this.props.prev();
      } else if (charCode === 39 || charCode === 40) {
        this.props.next();
      }
    }
  }
```

**Comment by pixelass** [comment]
btw... jsfmt uses "esformatter": "^0.5.1"

**Comment by royriojas** [comment]
try upgrading esformatter to 0.7.0 in the jsfmt folder

Also do you see the same behavior here?

http://requirebin.com/embed?gist=0d67452e01754269660f

Paste you code above and see if you can see the same issue you're mentioning

**Comment by royriojas** [comment]
O so I just test this:

```javascript
class someClass {
handleKeyup(e) {
  if (this.props.listen) {
      let charCode = e.which;
      if (charCode === 37 || charCode === 38) {
        this.props.prev();
      } else if (charCode === 39 || charCode === 40) {
        this.props.next();
      }
    }
  }
}
```
And get this

```javascript
class someClass {
  handleKeyup(e) {
    if (this.props.listen) {
      let charCode = e.which;
      if (charCode === 37 || charCode === 38) {
        this.props.prev();
      } else if (charCode === 39 || charCode === 40) {
        this.props.next();
      }
    }
  }
}
```
So basically if you want to format es6 code, I suggest try upgrading to `esformatter@0.7.0` can you verify this working on the test page?

**Comment by ipselon** [comment]
@royriojas thanks a lot.
version 0.7.1 of esformatter + version 1.3.0 of esformatter-jsx work perfectly.

Could you provide options for beautifier in case when there is JSX tag inside of attribute of another JSX tag ? 

See example of __Button__ in __buttonAfter__ attribute below:

Before:
```
            <Input 
                ref='inputElement'
                value={this.state.urlValue}
                type={ 'text'} 
                label={ this.props.label} 
                placeholder={ 'Enter value'} 
                addonBefore={ 'URL:'} 
                onChange={this._handleChangeUrlValue}
                buttonAfter={ <Button 
                                onClick={this._handleClearUrlValue}
                                bsStyle={ 'default'}>
                                <span className={ 'fa fa-times'}></span>
                              </Button> }>
                <Grid>
                    <Row>
                        <Col/>
                    </Row>
                </Grid>
            </Input>
```
After
```
            <Input ref='inputElement'
                   value={this.state.urlValue}
                   type={ 'text'}
                   label={ this.props.label}
                   placeholder={ 'Enter value'}
                   addonBefore={ 'URL:'}
                   onChange={this._handleChangeUrlValue}
                   buttonAfter={ <Button onClick={this._handleClearUrlValue} bsStyle={
            'default'}>
            <span className={ 'fa fa-times'}></span>
            </Button> }>
            <Grid>
                <Row>
                    <Col/>
                </Row>
            </Grid>
            </Input>
```

**Comment by pixelass** [comment]
I updated to esformatter 0.7.1 with esformatter.jsx 1.0.3

now it's working fine..
There are other issues.. but not related to this topic.

**Comment by royriojas** [comment]
@ipselon I have faced that issue before, so far is a known bug, and the only solution for now is to extract that block to its own variable. Can you file that under a different bug? I might get some time to try that today.

**Comment by ipselon** [comment]
Thanks.

**Comment by royriojas** [comment]
@pixelass thanks for your help to debug this issue. So basically `esformatter@0.7.1` and `esformatter-jsx@1.3.0` is what is recommended if you want to beautify code with ES6 syntax
