### ISSUE TITLE
Request - Option for multi-line styles

### ISSUE THREAD

**Issue by rkhayat** [royriojas/esformatter-jsx#30]
Styles seem to be compacted on one line, is there any options for having them be on multiple lines?

```
  style={{
                display: 'table',
                whiteSpace: 'nowrap',
                 width: '100%',
                 height: '100%',
                 overflowX:'auto'
             }}
```

**Comment by royriojas** [comment]
closed by https://github.com/royriojas/esformatter-jsx/commit/7f898460f4e4f2697e493176c91f99fc4d36bff1. In this case if you want the styles in multiple lines you can use: `JSXExpressionsSingleLine: false` in your configuration.
