### ISSUE TITLE
Upgrade to babel 6.0

### ISSUE THREAD

**Issue by LinusU** [royriojas/esformatter-jsx#38]
This message currently gets printed when installing via npm.

> npm WARN deprecated babel-core@5.8.33: Babel 5 is no longer being maintained. Upgrade to Babel 6.

**Comment by royriojas** [comment]
Will upgrade, thanks for reporting it

**Comment by royriojas** [comment]
I actually tried to do the upgrade. It seems that is not something possible without finding how to make the babylon parser to understand the bind short hand "`::`". Something not really that possible.

**Comment by LinusU** [comment]
It is very easily solved. Use the [stage-0 preset](https://www.npmjs.com/package/babel-preset-stage-0) since the function bind operator is in stage zero.

Alternatively you can add just the [function bind plugin](https://www.npmjs.com/package/babel-plugin-transform-function-bind).

**Comment by royriojas** [comment]
@LinusU  not really, `esformatter-jsx` in reality uses babylon, not babel-core. as I mention, I made the changes to use babylon [here](https://github.com/royriojas/esformatter-jsx/commit/4d7518865525e074353c3f940326961f8a8372f8) if you can configure babylon to make the tests pass it would be awesome! I won't have time to investigate it this weekend.

Regards

**Comment by LinusU** [comment]
Ah, I see, thanks for explaining. I'll try to have a look at it :)

**Comment by royriojas** [comment]
@LinusU actually your suggestion drove me in the right direction. I was successful replacing `babel-core` with babylon. I had made a major release, since I don't know what other syntax might be needed to be enabled. 

`esformatter-jsx@3.0.0` won't print that deprecation warning.

**Comment by LinusU** [comment]
Super, thank you!
