### ISSUE TITLE
JSX indentation working on CLI but not in Sublime Text

### ISSUE THREAD

**Issue by doque** [royriojas/esformatter-jsx#46]
The code I'm trying to format:
https://gist.github.com/doque/6573bd5b1e6762ec0b7e

My `jsfmt.sublime-settings` file contains these options:

    {
        "autoformat": false,
        "extensions": [
            "js",
            "jsx",
            "sublime-settings"
        ],
        "jsx": {
            "alignWithFirstAttribute": true,
            "attrsOnSameLineAsTag": true,
            "firstAttributeOnSameLine": false,
            "formatJSX": true,
            "maxAttrsOnTag": 1
        },
        "plugins": [
            "esformatter-jsx"
        ]
    }

I've also got an `.esformatter` file in the project directory:

    {
        "plugins": [
            "esformatter-jsx"
        ],
        "jsx": {
            "formatJSX": true,
            "attrsOnSameLineAsTag": false,
            "maxAttrsOnTag": 1,
            "firstAttributeOnSameLine": true,
            "spaceInJSXExpressionContainers": " ",
            "alignWithFirstAttribute": true,
            "htmlOptions": {
                "brace_style": "collapse",
                "indent_char": " ",
                "indent_size": 4,
                "max_preserve_newlines": 2,
                "preserve_newlines": true

            }
        }
    }

Versions I'm using:

    user@project> npm ls esformatter
	ezone@1.0.0 /path/
	└── esformatter@0.8.1

	user@project> npm ls esformatter-jsx
	ezone@1.0.0 /path/
	└── esformatter-jsx@4.0.6

**Running `esformatter` from command line yields the desired result:**
https://gist.github.com/doque/f3132ec691202996d4b7

However, running `JSFMT - Format current file` from Sublime does not indent the JSX correctly. It remains unindented.

**Comment by royriojas** [comment]
hi @doque, did you follow the instructions posted [here](https://github.com/royriojas/esformatter-jsx/wiki/Usage-with-jsfmt)?

**Comment by doque** [comment]
Yes, I did. I posted my settings file above.

**Comment by royriojas** [comment]
Can you please check the sublime console? To see if any error had occurred

**Comment by zkilgore** [comment]
I am having the same issue with Sublime Text 3. The error I get in the Sublime console is:

    JSFMT ==>
    Error: module.js:339
        throw err;
        ^

    Error: Cannot find module 'get-stdin'
        at Function.Module._resolveFilename (module.js:337:15)
        at Function.Module._load (module.js:287:25)
        at Module.require (module.js:366:17)
        at require (module.js:385:17)
        at Object.<anonymous> (/Users/zacharykilgore/Library/Application Support/Sublime Text 3/Packages/jsfmt/jsfmt.js:3:13)
        at Module._compile (module.js:425:26)
        at Object.Module._extensions..js (module.js:432:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:311:12)
        at Function.Module.runMain (module.js:457:10)

**Comment by sowdri** [comment]
There is an error in the documentation:
https://github.com/royriojas/esformatter-jsx/wiki/Usage-with-jsfmt

In the following file, `plugins` should be inside `options`.
```
{
  "extensions":
    [
      "js",
      "jsx",
      "sublime-settings"
    ],
  "plugins":
  [
    "esformatter-jsx",
  ],
  "jsx": {
    "formatJSX": true,
    // change these to your preferred values
    // refer to https://github.com/royriojas/esformatter-jsx#best-configuration for more options
    "attrsOnSameLineAsTag": false, 
    "maxAttrsOnTag": 1,
    "firstAttributeOnSameLine": false,
    "alignWithFirstAttribute": true
  }
}
```

Try this version: (works)
```
{
  "extensions": [
    "js",
    "jsx",
    "sublime-settings"
  ],
  "options": { 
    "plugins": [
      "esformatter-jsx",
    ]
  },
  "jsx": {
    "formatJSX": true,
    // change these to your preferred values
    // refer to https://github.com/royriojas/esformatter-jsx#best-configuration for more options
    "attrsOnSameLineAsTag": false,
    "maxAttrsOnTag": 1,
    "firstAttributeOnSameLine": false,
    "alignWithFirstAttribute": true
  }
}
```

**Comment by royriojas** [comment]
@sowdri thank you for your help

hi guys can you confirm the changes proposed by @sowdri worked? It would be nice to update to update the documentation.

**Comment by tnrich** [comment]
I can confirm these changes work

**Comment by royriojas** [comment]
closing it as the proposed changes made this work.
