### ISSUE TITLE
___AVOID_ESFMT_BUG_WITH_COMMENTS__;

### ISSUE THREAD

**Issue by maitriyogin** [royriojas/esformatter-jsx#58]
Why is this getting amended inside every function?
/Stephen.

**Comment by royriojas** [comment]
I'm sorry @maitriyogin it is most than probably an awful bug for the awful hacks I had to do. Can you provide an example of the code that is producing this bug? this for certain should never happen.

**Comment by mmazzarolo** [comment]
Hey there, same issue.
Here is an example (react-native):
```javascript
import React, { StatusBar, View } from 'react-native'
import Router from './router'
import { Provider } from 'react-redux'
import Colors from './theme/colors'
import configureStore from './store/configureStore'
const store = configureStore()

export default class Tony extends React.Component {
  render () {
    return (
      <View style={{ flex: 1 }}>
        <StatusBar barStyle='light-content' backgroundColor={Colors.PURPLE_MAIN_DARK} />
        <Provider store={store}>
          <Router />
        </Provider>
      </View>
    )
  }
}
```

Results:
```javascript
import React, { StatusBar, View } from 'react-native'
import Router from './router'
import { Provider } from 'react-redux'
import Colors from './theme/colors'
import configureStore from './store/configureStore'
const store = configureStore()

export default class Tony extends React.Component {
  render() {
    return (
      <View style={{ flex: 1 }}>
        <StatusBar barStyle='light-content' backgroundColor={Colors.PURPLE_MAIN_DARK} />
        <Provider store={store}>
          <Router />
        </Provider>
      </View>
    )

    ___AVOID_ESFMT_BUG_WITH_COMMENTS__
  }
}

```

**Comment by royriojas** [comment]
That's weird I just ran this against the latest version of `esformatter-jsx` but I can't reproduce it. Can you provide your esformatter configuration?

**Comment by trajano** [comment]
I have the same issue here's my config.
```
{
  "root": true,
  "plugins": [
    "esformatter-asi",
    "esformatter-jsx",
    "esformatter-limit-linebreaks",
    "esformatter-quotes",
    "esformatter-quote-props",
    "esformatter-remove-trailing-commas"
  ],
  "LimitLineBreaks": 2,
  "quotes": {
    "type": "single"
  },
  "whiteSpace": {
    "after": {
      "FunctionName": 1,
      "FunctionReservedWord": 1,
      "MethodDefinitionName": 1
    }
  }
}

```

**Comment by royriojas** [comment]
hi @trajano can you please share a snippet of the code that cause the issue? Also, is that the full config?

**Comment by trajano** [comment]
To fix it is just one character change.  I'll point it out

**Comment by trajano** [comment]
Key thing to note, I'm using `esformatter-asi` so that will remove the `;` that are not needed.  @maitriyogin and @mmazzarolo  I am presuming you are doing the same.

**Comment by royriojas** [comment]
@trajano that might make sense. I will add your suggestion to the regex that should fix the issue.

**Comment by trajano** [comment]
Pls make a release soon :+1:

**Comment by royriojas** [comment]
Incorrectly marked the wrong issue as closed... but this is already closed and published as `esformatter-jsx@5.0.4` Thanks for the help @trajano

**Comment by trajano** [comment]
Just confirmed on https://github.com/trajano/meteor-boilerplate/tree/react I think you can close this.

**Comment by royriojas** [comment]
nice @trajano. Thanks for your help.

**Comment by trajano** [comment]
NP, too bad we can't get esformatter to format it the way `standard-react` wants.  I had to do two rules but it's fine

    "react/jsx-curly-spacing": [2, "always"],
    "react/jsx-indent": 0
