### ISSUE TITLE
Formatting guidelines

### ISSUE THREAD

**Issue by kevinsimper** [royriojas/esformatter-jsx#6]
I was wondering if it is possible to format the code with `esformatter-jsx` like they do on the React website?

https://facebook.github.io/react/docs/tutorial.html

Here they format code with `return ()`, where the end parenthese is at the same level as the return statement.

I am sorry if i missed in the readme, if it exist, then i can provide a pull request to show an example.

**Comment by royriojas** [comment]
Not sure exactly what you mean with that, can you please provide an example of the formatting that does not follow those guidelines?

Using the online tool
http://requirebin.com/embed?gist=0d67452e01754269660f

I can check that almost all the examples are formatted correctly. I do find an instance where it fail, and I will try to fix that over the weekend

Can you please elaborate a bit more?

**Comment by kevinsimper** [comment]
For example this code:
https://facebook.github.io/react/tips/communicate-between-components.html
```
var GroceryList = React.createClass({
  handleClick: function(i) {
    console.log('You clicked: ' + this.props.items[i]);
  },

  render: function() {
    return (
      <div>
        {this.props.items.map(function(item, i) {
          return (
            <div onClick={this.handleClick.bind(this, i)} key={i}>{item}</div>
          );
        }, this)}
      </div>
    );
  }
});

React.render(
  <GroceryList items={['Apple', 'Banana', 'Cranberry']} />, mountNode
);
```

But is formatted like this on the requirebin

```
var GroceryList = React.createClass({
  handleClick: function(i) {
    console.log('You clicked: ' + this.props.items[i]);
  },

  render: function() {
    return (
      <div>
        {this.props.items.map(function(item, i) { return (
        <div onClick={this.handleClick.bind(this, i)} key={i}>{item}</div>
        ); }, this)}
      </div>
      );
  }
});

React.render(
  <GroceryList items={[ 'Apple', 'Banana', 'Cranberry']} />, mountNode
);
```

**Comment by royriojas** [comment]
I see, it is valid point, will work on make the formatter to try to respect the formatting of the React code block examples.

In the meantime, I guess that the workaround in the Readme could help:
https://github.com/royriojas/esformatter-jsx#nested-jsx-elements-and-ternary-operators

```javascript
var GroceryList = React.createClass( {
  handleClick: function ( i ) {
    console.log( 'You clicked: ' + this.props.items[ i ] );
  },
  render: function () {
    var items = this.props.items.map( function ( item, i ) {
      return <div onClick={ this.handleClick.bind( this, i )} key={i}>
               {item}
             </div>;
    }, this );

    return <div>
             {items}
           </div>;
  }
} );

React.render(
  <GroceryList items={ [ 'Apple', 'Banana', 'Cranberry' ]} />, mountNode
);

```

**Comment by kevinsimper** [comment]
Could be really cool if it could format it like the examples! :+1: 

I kind of dislike the workaround since you have to have one long return statement with a semicolon.

**Comment by kevinsimper** [comment]
@royriojas Can you provide a small hint, if I wanted to help with this?

**Comment by royriojas** [comment]
Sure, there are 2 things we should do

- see if we can use rocambole to parse the code instead of the parser we're using now
- Identify the node type of the inline JSX javascript structure.
- decide if we want to treat them as regular javascript. If not we should prevent them from being formatted by `esformatter`
- finally decide how to format those stuctures, maybe using esformatter again, but only on the inline JSX structures...

**Comment by royriojas** [comment]
@kevinsimper I have been trying really hard to fix this, and it has been really hard, the more I think about it the more I realize the only way I have right now to fix this, without making this excessive complex it is to actually to offer a way to not format the code inside the `JSXExpressionContainer` but even in this case, there are lot of corner cases that will be really hard to take into consideration.

I will keep this open and I'm open to receive any pull request that attempt to fix this issue. The only requirement is that all the unit tests are honored.

I will attempt again in a sometime in the future but right now I have spent too much time on this without actually find a proper solution for it.

**Comment by vvo** [comment]
> Here they format code with return (), where the end parenthese is at the same level as the return statement.
> 
> I am sorry if i missed in the readme, if it exist, then i can provide a pull request to show an example.

It would be really awesome to be able to autoformat JSX using the react style. I like it too, very readable

**Comment by royriojas** [comment]
Latest version of `esformatter-jsx` handle a lot better the nested structures. I'm closing this issue for now, if you believe this still not enough, feel free to reopen the bug or make a pull request :)
