### ISSUE TITLE
Demo appears to be broken

### ISSUE THREAD

**Issue by tnrich** [royriojas/esformatter-jsx#61]
![image](https://cloud.githubusercontent.com/assets/2730609/14504912/a60582f0-016b-11e6-8dbc-13b2fb6ef936.png)

**Comment by royriojas** [comment]
Hi Tomas, yes It seems somehow esformatter@latest cannot be browserified (not sure why) I tried to revert to the latest working version of the demo, one that uses an old version of esformatter, but requirebin was having issues with the update :(

In any case will try it again soon. Thanks for the report!
