### ISSUE TITLE
format with beautify in sublime

### ISSUE THREAD

**Issue by kaktus42** [royriojas/esformatter-jsx#65]
I installed jsfmt and esformatter-jsx like here:
https://github.com/royriojas/esformatter-jsx/wiki/Usage-with-jsfmt
And installed beautify globally with npm.

The javascript-part gets formatted okay, but the jsx part is not processed by beautify.

My jsfmt.sublime-settings:

```
{
  "autoformat": true,
  "extensions": [
    "js",
    "jsx",
    "sublime-settings"
  ],
  "jsx": {
    "alignWithFirstAttribute": true,
    "attrsOnSameLineAsTag": false,
    "firstAttributeOnSameLine": false,
    "formatJSX": true,
    "maxAttrsOnTag": 1,
    "htmlOptions": { // same as the ones passed to js-beautifier.html
      "brace_style": "collapse",
      "indent_char": " ",
      "indent_size": 2,
      "max_preserve_newlines": 2,
      "preserve_newlines": true
    //wrap_line_length: 250
    }
  },
  "plugins": [
    "esformatter-jsx",
  ]
}
```

I also tried with console: `esformatter <FILE>` with a .esformatter with the config from here: https://github.com/royriojas/esformatter-jsx#config
And that works fine.

What can I do make it work in sublime? Can I maybe also load the config file from the project dir into sublime?

**Comment by royriojas** [comment]
Hi @kaktus42 

JSFMT updated the configuration file, I have updated the wiki page to match https://github.com/royriojas/esformatter-jsx/wiki/Usage-with-jsfmt

now the configuration for JSFMT goes inside the `options` key

**Comment by kaktus42** [comment]
yes, perfect!
thanks
