### ISSUE TITLE
"The formatting failed..."

### ISSUE THREAD

**Issue by yanickrochon** [royriojas/esformatter-jsx#66]
I'm not certain, but I believe fsFmt is looking for Node.js and can't find it. Here is the console output :

```
error: The formatting failed please check the console for more details.

JSFMT ==>
Couldn't find Node.js. Make sure it's in your
            $PATH by running `node -v` in your command-line.
```

The thing is that I am using nvm and the `node` executable *is* available from the console. I have `0.12`, `4.1` to `4.4`, `5.8`, and `6.0` installed; the default one being `6.0` right now. My PATH env variable does contain the correct path. I'm not sure what's wrong.

**Comment by royriojas** [comment]
hi @yanickrochon I assume the issue you have is related to sublime text and jsfmt right? I can try to provide some help, but it might be good for you to report the issue in the jsfmt repo.

First have you tried this guide? I just updated it to match the latest JSFMT configuration info:
https://github.com/royriojas/esformatter-jsx/wiki/Usage-with-jsfmt

Also please check:
https://github.com/ionutvmi/sublime-jsfmt#installation

Let me know if that helps

**Comment by royriojas** [comment]
@yanickrochon closing as not more comments were done. Feel free to reopen.
