### ISSUE TITLE
How to configure formatting of destruction assignment? 

### ISSUE THREAD

**Issue by captainkovalsky** [royriojas/esformatter-jsx#69]
I wanna to format

```
const {fields: {firstName, lastName, email, date, location}, handleSubmit, resetForm, submitting, intl, _l} = this.props;
```

to 

```
const {fields: {
firstName, 
lastName, 
email, 
date, 
location}, 
handleSubmit, 
resetForm, 
submitting, 
intl,
 _l} = this.props;

```

**Comment by royriojas** [comment]
I myself tried to find a way to make this to happen. The only way I found was to use the ignore comments: 

[demo](http://royriojas.com/resources/esformatter-jsx/#%7B%22config%22%3A%7B%22jsx%22%3A%7B%22attrsOnSameLineAsTag%22%3Afalse%2C%22maxAttrsOnTag%22%3A1%2C%22firstAttributeOnSameLine%22%3Atrue%2C%22alignWithFirstAttribute%22%3Atrue%2C%22JSXExpressionsSingleLine%22%3Afalse%2C%22removeSpaceBeforeClosingJSX%22%3Afalse%7D%7D%2C%22code%22%3A%22const%20%7Bfields%3A%20%7BfirstName%2C%20lastName%2C%20email%2C%20date%2C%20location%7D%2C%20handleSubmit%2C%20resetForm%2C%20submitting%2C%20intl%2C%20_l%7D%20%3D%20this.props%3B%5Cn%5Cn%2F*%20esfmt-ignore-start%20*%2F%5Cnconst%20%7Bfields%3A%20%7B%5CnfirstName%2C%20%5CnlastName%2C%20%5Cnemail%2C%20%5Cndate%2C%20%5Cnlocation%7D%2C%20%5CnhandleSubmit%2C%20%5CnresetForm%2C%20%5Cnsubmitting%2C%20%5Cnintl%2C%5Cn%20_l%7D%20%3D%20this.props%3B%5Cn%2F*%20esfmt-ignore-end%20*%2F%22%7D)

```javascript
const {fields: {firstName, lastName, email, date, location}, handleSubmit, resetForm, submitting, intl, _l} = this.props;

/* esfmt-ignore-start */
const {fields: {
firstName, 
lastName, 
email, 
date, 
location}, 
handleSubmit, 
resetForm, 
submitting, 
intl,
 _l} = this.props;
/* esfmt-ignore-end */
```

newer [esformatter](https://github.com/millermedeiros/esformatter) has more options now, so you might want also to take a look there. Maybe you'll find some way to control the lines after the commas in destructuring...

**Comment by royriojas** [comment]
@vdzundza you might also want to ask this question in the esformatter repo. Probably is the right place to add the question

**Comment by pbojinov** [comment]
did you guys end up finding a setting for this?

**Comment by AdamSalma** [comment]
@pbojinov @furydam @royriojas 

Try this:

```
"lineBreak":  {
  "before": {
    "ExportAllDeclaration": -1,
    "ExportDefaultDeclaration": -1,
    "ExportNamedDeclaration": -1,
    "ModuleSpecifierClosingBrace": 1,
    "ModuleSpecifierComma": 0,
    "ObjectPatternClosingBrace": 1,
  },
  "after": {
    "ExportAllDeclaration": -1,
    "ExportDefaultDeclaration": -1,
    "ExportNamedDeclaration": -1,
    "ImportDeclaration": 2,
    "ModuleSpecifierOpeningBrace": 1,
    "ModuleSpecifierClosingBrace": -1,
    "ModuleSpecifierComma": 1,

    "ObjectPatternComma": 1,
    "ObjectPatternOpeningBrace": 1,

    "FunctionDeclarationOpeningBrace": -1
  }
}
```

Specifically look at the ```ObjectPattern``` rules as they define linebreaks before/after a comma inside an object literal.
