### ISSUE TITLE
Template or backtick strings keep being indented

### ISSUE THREAD

**Issue by ckknight** [royriojas/esformatter-jsx#72]
This is likely related to #53, but occurs regardless if `formatJSXExpressions` is true or false

Using esformatter 0.9.3 and esformatter-jsx 5.0.4

.esformatter:
```json
{
	"preset": "default",
	"plugins": [
		"esformatter-jsx"
	]
}
```

Initial input:
```jsx
function render(count) {
    return (
        <FormattedMessage
            id="some.id"
            defaultMessage={`You have {count, plural,
                =0 {no Items}
                one {one Item}
                other {{count} Items}
            }`}
            description="Description goes here"
            values={{ count }}
        />
    );
}
```

First output:
```jsx
function render(count) {
  return (
    <FormattedMessage id="some.id" defaultMessage={ `You have {count, plural,
                                                                =0 {no Items}
                                                                one {one Item}
                                                                other {{count} Items}
                                                            }` } description="Description goes here" values={ { count } } />
    );
}
```

Second output:
```jsx
function render(count) {
  return (
    <FormattedMessage id="some.id" defaultMessage={ `You have {count, plural,
                                                                                                                =0 {no Items}
                                                                                                                one {one Item}
                                                                                                                other {{count} Items}
                                                                                                            }` } description="Description goes here" values={ { count } } />
    );
}
```

Third output:
```jsx
function render(count) {
  return (
    <FormattedMessage id="some.id" defaultMessage={ `You have {count, plural,
                                                                                                                                                                =0 {no Items}
                                                                                                                                                                one {one Item}
                                                                                                                                                                other {{count} Items}
                                                                                                                                                            }` } description="Description goes here" values={ { count } } />
    );
}
```

Also see #70 for a PR to verify reformatting

**Comment by royriojas** [comment]
definitively an ugly bug. :( 

Will try to take a look at it now

**Comment by royriojas** [comment]
I just published a new version with this fixed. Let me know if there is any instance where it fails...

[demo](http://royriojas.com/resources/esformatter-jsx/#%7B%22config%22%3A%7B%22jsx%22%3A%7B%22attrsOnSameLineAsTag%22%3Afalse%2C%22maxAttrsOnTag%22%3A1%2C%22firstAttributeOnSameLine%22%3Atrue%2C%22alignWithFirstAttribute%22%3Atrue%7D%7D%2C%22code%22%3A%22function%20render(count)%20%7B%5Cn%20%20%20%20return%20(%5Cn%20%20%20%20%20%20%20%20%3Cdiv%3E%5Cn%20%20%20%20%20%20%20%20%3CFormattedMessage%5Cn%20%20%20%20id%3D%5C%22some.id%5C%22%5Cn%20%20%20%20defaultMessage%3D%7B%60You%20have%20%7Bcount%2C%20plural%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3D0%20%7Bno%20Items%7D%5Cn%20%20%20%20%20%20%20%20one%20%7Bone%20Item%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20other%20%7B%7Bcount%7D%20Items%7D%20%24%7Binterpolated(%60s1_%24%7B2%7D%60)%7D%5Cn%20%20%20%20%7D%60%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20description%3D%5C%22Description%20goes%20here%5C%22%5Cn%20%20%20%20%20%20%20%20%20%20%20%20values%3D%7B%7B%20count%20%7D%7D%5Cn%20%20%20%20%20%20%20%20%2F%3E%5Cn%20%20%20%20%20%20%20%20%3CMDBlock%3E%5Cn%20%20%20%20%20%20%20%20%7B%5Cn%20%20%20%20%20%20%20%20%60You%20have%20%7Bcount%2C%20plural%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3D0%20%7Bno%20Items%7D%5Cn%20%20%20%20%20%20%20%20one%20%7Bone%20Item%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20other%20%7B%7Bcount%7D%20Items%7D%5Cn%20%20%20%20%20%20%20%20%7D%60%7D%5Cn%20%20%20%20%20%20%20%20%3C%2FMDBlock%3E%5Cn%20%20%20%20%20%20%20%20%3C%2Fdiv%3E%5Cn%20%20%20%20)%3B%5Cn%7D%22%7D)

**Comment by ckknight** [comment]
@royriojas Your demo duplicates the backtick string in the inner backtick string.

Also, the indentation bug is present if you do something akin to 

```jsx
<Comp prop={fn`
  hello
`}
```

**Comment by royriojas** [comment]
@ckknight I have to update the demo to use the latest. That shouldn't be happening with the latest.

For the other one I will investigate. Would you matter to create a new issue for the tags in backtips? please.
