### ISSUE TITLE
Support decorator on same line as property

### ISSUE THREAD

**Issue by arminrosu** [royriojas/esformatter-jsx#73]
Hello,

We are using a lot of decorators with properties, on the same line. e.g.

```js
export default class DecoratorTest {
    @readonly width = 100;
}
```
 
Unfortunately, this throws an error: `Unexpected token (2:62)`. Adding a line break between them fixes this issue. It would be nice if it could either format it itself or leave it as it is.

Here is my `.esformatter`:

```json
{
	"preset": "default",
	"root": true,
	"indent": {
		"value": "  "
	},
	"plugins": [
        "esformatter-jsx"
	]
}
```

Last but not least, thanks for this great plugin!

**Comment by royriojas** [comment]
Hi @arminrosu, yes I noticed that issue when starting using mobx...

Will fix it!

**Comment by arminrosu** [comment]
Awesome, thanks :)
