### ISSUE TITLE
Weird semicolon issue

### ISSUE THREAD

**Issue by schleumer** [royriojas/esformatter-jsx#78]
if i have a script like this:

```
const obj = {
  fn() {
    return {
      "hello": "world"
    }
  }
}
```

a exception is thrown:  `//==> Error: Unexpected token (5:5)`.

It's a valid expression.

**Comment by royriojas** [comment]
[demo](http://royriojas.com/resources/esformatter-jsx/?2#%7B%22config%22%3A%7B%22jsx%22%3A%7B%22attrsOnSameLineAsTag%22%3Afalse%2C%22maxAttrsOnTag%22%3A1%2C%22firstAttributeOnSameLine%22%3Afalse%2C%22alignWithFirstAttribute%22%3Atrue%7D%7D%2C%22code%22%3A%22const%20obj%20%3D%20%7B%5Cn%20%20abc%3A%20'2'%2C%5Cn%20%20fn()%20%7B%5Cn%20%20%20%20return%20%7B%5Cn%20%20%20%20%20%20hello%3A%20'world'%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%5Cn%22%7D)

**Comment by schleumer** [comment]
Thanks!
