### ISSUE TITLE
Wrong indentation with ES6 

### ISSUE THREAD

**Issue by 0x80** [royriojas/esformatter-jsx#8]
```javascript
export default class ActiveMeeting extends Component {
  renderAttendees() {
    return this.props.meeting.attendees.map((attendee) => {
      return <Attendee key={attendee.displayName} profile={attendee}/>
    })
  }
}
```

turns into

```javascript
export default class ActiveMeeting extends Component {
  renderAttendees() {
    return this.props.meeting.attendees.map((attendee) => {
      return <Attendee key={attendee.displayName} profile={attendee}/>
      })
    }
  }
```

See also https://github.com/millermedeiros/esformatter/issues/337

**Comment by royriojas** [comment]
Hi, it is working fine for me. I tried it here: http://requirebin.com/embed?gist=0d67452e01754269660f

this input 
```javascript
export default class ActiveMeeting extends Component {
  renderAttendees() {
    return this.props.meeting.attendees.map((attendee) => {
      return <Attendee key={attendee.displayName} profile={attendee}/>
    })
  }
}
```

generates this output

```javascript
export default class ActiveMeeting extends Component {
  renderAttendees() {
    return this.props.meeting.attendees.map( (attendee) => {
      return <Attendee key={attendee.displayName} profile={attendee}/>
    } )
  }
}
```

Can you provide the version of esformatter, esformatter-jsx and a copy of your esformatter config? that might help to debug this issue

**Comment by 0x80** [comment]
I'm not using esformatter directly but through standard-format.

I just did another test with both installed

esformatter.............[0.7.1]
esformatter-jsx.........[1.3.0]
standard-format.........[1.4.0]

```standard-format es6class.js``` and ```esformatter es6class.js``` both give me the same output. I am not using any config file. I understood from the docs that esformatter loads its plugins automatically from the node_modules folder.

**Comment by royriojas** [comment]
well it seems the configuration that standard format uses is the one that is failing. I will close this bug. Have you reported that to them?

**Comment by 0x80** [comment]
Thanks for your help. I will report it to standard-format then
