### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by littlee** [royriojas/esformatter-jsx#82]
I found it runs so slow to use with Sublime Text (Sublime-Linter)

When using this plugin, it takes 10 sec to format the file
When not, it takes 1~2 sec to format the file, though JSX is not be formmatted

**Comment by royriojas** [comment]
hi @littlee 

Not sure I understand the issue correctly, I haven't use this plugin with sublime-linter, not sure how are you using it, can you provide more details on how is that you're using this from sublime text?

So far the only way I tried it to use it with sublime was using `jsfmt` and performance wise I never had issues, also a reduced test case of the code with issues will definitively help

Can you try here and see if the performance issue is reproducible? 10s seems like too much time

royriojas.com/resources/esformatter-jsx

**Comment by littlee** [comment]
My fault, what I use is "EsFormatter", let me try jsfmt

**Comment by royriojas** [comment]
Closing since there hasn't been any new activity on this issue and it might be caused because of the wrong tool was used.
