### ISSUE TITLE
map in jsx gets worse everytime the formatter is run

### ISSUE THREAD

**Issue by ByStones** [royriojas/esformatter-jsx#84]
The following code gets formatted in a really weird way and gets worse everytime the formatter is run.

Code as Gist because this editor kills spaces?
https://gist.github.com/ByStones/d5065dd54fccf9ad293fe48756edff30

esformatter: 0.6.9
esformatter-jsx: 7.0.1

**Comment by royriojas** [comment]
Hi @ByStones, 

Thanks for reporting the issue, yes there is a bug already opened for this behavior https://github.com/royriojas/esformatter-jsx/issues/53, I haven't had much time lately to fix issues, in any case PRs are welcome will close this as duplicated of #53
