### ISSUE TITLE
html in variables

### ISSUE THREAD

**Issue by spencermountain** [royriojas/esformatter-jsx#9]
hi Roy, thanks for making this great plugin.
I doubt it's best practice, but I sometimes do this:
```javascript
render:function(){
  var el1=<div></div>
  var el2=<div></div>
  return (<div>
    {el1}
    {el2}
  </div>)
}
```
which gets botched by the formatter.
all the best,

**Comment by royriojas** [comment]
hi @spencermountain, yes I'm aware of that issue as well, it does bother me a lot. I will try to spend some time to try to close the bugs related to the usage of jsx blocks. keep tuned :)

**Comment by royriojas** [comment]
hi @spencermountain check http://goo.gl/51kUEv I guess this should be fine now

**Comment by spencermountain** [comment]
nice! thanks
