### ISSUE TITLE
">>> undefined" appears in CLI output when using this plugin 

### ISSUE THREAD

**Issue by bigfish** [royriojas/esformatter-jsx#92]
having installed esformatter and esformatter-jsx globally, when I run the command 

    esformatter --plugins esformatter-jsx Foo.js

It formats appropriately, except I get output: 

>>> undefined
>>> undefined
import React, { PropTypes } from 'react';
import { reduxForm, change } from 'redux-form';
...

I have this no .esformatter file or other configuration. Using Mac OS X , iterm2, bash, node 5.

Any help appreciated, otherwise it works great.

**Comment by bigfish** [comment]
github changed the formatting of ">>>" to indent ! actually what appears is ">>>undefined" on first 2 lines.

**Comment by chenglou** [comment]
The published package contains that line in `lib/format-jsx.js`:

<img width="369" alt="screenshot 2016-11-25 19 42 56" src="https://cloud.githubusercontent.com/assets/1909539/20637810/6a31465e-b347-11e6-8305-55605805e0ff.png">

I couldn't find this in the commit history. It's possible that this line's been added before `npm publish` (which picks up local changes, not a clean state git checkout). @royriojas is it possible to re-publish this please?

**Comment by royriojas** [comment]
Sure, so sorry not sure how this line got into it. Fixing it now.

**Comment by royriojas** [comment]
@chenglou so sorry, a new version was published v7.3.2

**Comment by chenglou** [comment]
Works now, thanks a lot!

**Comment by bigfish** [comment]
yup, works for me too , thanks!
