### ISSUE TITLE
JSX replaced to <__JSXExpression_0_0 />

### ISSUE THREAD

**Issue by wKich** [royriojas/esformatter-jsx#97]
Here is the [link](http://royriojas.com/resources/esformatter-jsx/#%7B%22config%22%3A%7B%22jsx%22%3A%7B%22attrsOnSameLineAsTag%22%3Afalse%2C%22maxAttrsOnTag%22%3A1%2C%22firstAttributeOnSameLine%22%3Afalse%2C%22alignWithFirstAttribute%22%3Atrue%7D%7D%2C%22code%22%3A%22%5B%5Cn%20%20%3Cdiv%3E%5Cn%20%20%20%20%3Cspan%3E%5Cn%20%20%20%20%20%20%3CFoo%5Cn%20%20%20%20%20%20%20%20aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa%3D%5C%22%5C%22%5Cn%20%20%20%20%20%20%20%20bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb%3D%5C%22%5C%22%5Cn%20%20%20%20%20%20%2F%3E%5Cn%20%20%20%20%3C%2Fspan%3E%7B'foobar'%7D%5Cn%20%20%3C%2Fdiv%3E%2C%5Cn%20%20%5Cn%20%20%3Cdiv%3E%5Cn%20%20%20%20%3Cspan%3E%5Cn%20%20%20%20%20%20%3CFoo%5Cn%20%20%20%20%20%20%20%20aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa%3D%5C%22%5C%22%5Cn%20%20%20%20%20%20%20%20bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb%3D%5C%22%5C%22%5Cn%20%20%20%20%20%20%2F%3E%5Cn%20%20%3C%2Fspan%3E%7B'foobar'%7D%5Cn%20%20%3C%2Fdiv%3E%2C%5Cn%5D%22%7D) to online demo. I think it's close to #60, but has something different behavior.

**Comment by royriojas** [comment]
oh @wKich thanks for reporting this. Can you check if this is happening on latest version? (demo is not using the latest, will have to update it soon)

**Comment by wKich** [comment]
Checked on latest version, output the same.

**Comment by wKich** [comment]
I did some research and we can fixed this problem modify RegExp in this [line](https://github.com/royriojas/esformatter-jsx/blob/master/src/format-jsx.js#L87) to
```js
new RegExp(`<__JSXExpression_0_${  idx  }\\s*\\/>`);
```

Because `js-beautify` inserted new line character [here](https://github.com/beautify-web/js-beautify/blob/master/js/lib/beautify-html.js#L467) if `JSXExpression` placeholder tag follow by [unformatted](https://github.com/beautify-web/js-beautify/blob/master/js/lib/beautify-html.js#L154-L164) html tag and line length bigger then `wrap_line_length` option.

**Comment by wKich** [comment]
I try to make PR. But I think somewhere in options reading there is another bug. If I specify for my test case `htmlOptions.unformatted` default array from `js-beautify` package, then the other test cases after my will fail.
